### PR TITLE
POEM_004 Creating Interpolant Class For 1D Splines

### PR DESCRIPTION
**Pull request by DKilkenny**

### CODE REVIEW

**Comment by gbarter** [comment]
I fully support this POEM and definitely give a +1 "upvote"!

One comment around the statement and API for Standalone usage, 

> This simplicity and flexibility comes at a small cost of some performance, particularly when using the 'b-spline' method, as we aren't pre-computing any values for use in subsequent calls.

Why not allow for a more object-oriented instance of the interpolator like SciPy often uses?
`f = BSpline(xcp, ycp)`
`y1, dydx, dydxcp, dyycp = f(x1)`
`y2, dydx, dydxcp, dyycp = f(x2)`

**Comment by Kenneth-T-Moore** [comment]
> Why not allow for a more object-oriented instance of the interpolator like SciPy often uses?
> `f = BSpline(xcp, ycp)`
> `y1, dydx, dydxcp, dyycp = f(x1)`
> `y2, dydx, dydxcp, dyycp = f(x2)`

We were trying to preserve a way to use it as an interpolator and a dimension-reducing spline without requiring 2 separate functions.  An alternative would be:

f = BSpline()
f.train(x_train, y_train)
y1, dydx, dydxcp, dydycp = f.interpolate(x1)
y2, dydx, dydxcp, dydycp = f.interpolate(x2)

f.declare_spline(x, x_cp)
y1, dydx, dydxcp, dydycp = f.evaluate_spline(y_cp1)
y2, dydx, dydxcp, dydycp = f.evaluate_spline(y_cp2)

But I think we are open to ideas and suggestions about whether that would be too complicated.

**Comment by gbarter** [comment]
My suggestion isn't critical.  You have clearly thought about it.  This POEM describes a welcome change regardless.

**Comment by Kenneth-T-Moore** [comment]
I am starting to lean towards a more OO design, though.  Maybe I will try to propose something a little cleaner after refactoring.

**Comment by robfalck** [comment]
Accepted via #24

**Pull request closed without merging**
